services:
  neo_database:
    image: neo4j:5.21
    container_name: neo4j-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      #NEO4J_dbms_memory_pagecache_size: 512M
      #NEO4J_dbms_memory_heap_initial__size: 512M
      #NEO4J_dbms_memory_heap_max__size: 512M
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: