version: '3'
services:
  neo_database:
    image: neo4j:5.21
    container_name: neo4j-community
    ports:
      - "7474:7474"    # HTTP Port
      - "7687:7687"    # Bolt Port
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}   # Username and Password for Neo4j Authentication
      NEO4J_PLUGINS: '["apoc", "graph-data-science", "bloom"]'   # Installing APOC and GDS Plugins
      NEO4J_apoc_import_file_enabled: "true"            # Enabling APOC Import
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*, bloom.*
      NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:7687"  # Allow remote access to Bolt
      NEO4J_dbms_connector_http_listen__address: "0.0.0.0:7474"  # Allow remote access to HTTP
      NEO4J_apoc_initial__cypher__run: "GRANT WRITE ON GRAPH * NODES * TO neo4j; GRANT DELETE ON GRAPH * RELATIONSHIPS * TO neo4j;"
      # Optional Memory Settings for Neo4j
      #NEO4J_dbms_memory_pagecache_size: 512M
      #NEO4J_dbms_memory_heap_initial__size: 512M
      #NEO4J_dbms_memory_heap_max__size: 512M
    volumes:
      - neo4j_data:/data       # Persistent data storage
      - neo4j_logs:/logs       # Log files
      - neo4j_import:/var/lib/neo4j/import  # Import directory for files
      - neo4j_plugins:/plugins  # Plugin directory for APOC and GDS

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: